import { Toaster } from "sonner"
import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ConvexClientProvider } from "@/components/providers/convex-provider";
import { EdgeStoreProvider } from "@/lib/edgestore";


export const metadata: Metadata = {
  title: "BoccNote",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressContentEditableWarning>
      <body>
        <ConvexClientProvider>
          <EdgeStoreProvider>
            {/* <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
              storageKey="boccnote-theme-2"
            > */}
            <Toaster position="bottom-center" />
            {children}

            {/* </ThemeProvider> */}
          </EdgeStoreProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
